# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deployment Testing

on:
  push:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Development
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test --if-present
    
    - name: git checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.INTEGRATIONS_TOKEN }}

    # https://github.com/marketplace/actions/github-pull-request-action
    - name: create pull request
      id: open-pr
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.INTEGRATIONS_TOKEN }}
        destination_branch: ${{ github.event.repository.default_branch }}
        pr_title: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
        pr_body: "Automated Pull Request"
        pr_reviewer: "${{ secrets.ASSIGNEE }}"
        pr_assignee: "${{ secrets.ASSIGNEE }}"

    # https://github.com/marketplace/actions/enable-pull-request-automerge
    - name: enable automerge
      if: steps.open-pr.outputs.pr_number != ''
      uses: peter-evans/enable-pull-request-automerge@v2
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
        merge-method: merge

